version: 0.2

phases:
  pre_build:
    commands:
      - echo Starting build
  build:
    commands:
      - echo running tests
      - gradle test
      - echo creating jar
      - gradle clean build
artifacts:
  files:
    - build/libs/marketplace-projector-1.0-SNAPSHOT.jar
    - appspec.yml